/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import UserInterface.Airliner.WorkAreaAirliner;
import UserInterface.ManageAirlines.AirlinerLogin;
import java.awt.CardLayout;
import Busniess.AirlinerDirectory;
import Busniess.CustomerDirectory;
import UserInterface.Customer.ManageCustomer;
import Busniess.Airliner;
import Busniess.Seat;
import Busniess.TravelAgencyClass;


/**
 *
 * @author varad
 */
public class MainJFrame extends javax.swing.JFrame {
    private AirlinerDirectory airlinerDirectory;
    private CustomerDirectory customerDirectory;
    private Airliner airliner;
    private TravelAgencyClass travelAgency;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        
        airlinerDirectory = new AirlinerDirectory();
        customerDirectory = new CustomerDirectory();
        travelAgency = new TravelAgencyClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CardSequenceJPanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Customer = new javax.swing.JButton();
        ManageAirliners = new javax.swing.JButton();
        btnTravelAgency = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CardSequenceJPanel.setBackground(new java.awt.Color(204, 204, 204));
        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CardSequenceJPanel);

        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Customer.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        LeftPanel.add(Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 50));

        ManageAirliners.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ManageAirliners.setText("ManageAirlines");
        ManageAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAirlinersActionPerformed(evt);
            }
        });
        LeftPanel.add(ManageAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 100, 50));

        btnTravelAgency.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnTravelAgency.setText("TravelAgency");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        LeftPanel.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 100, 50));

        jSplitPane1.setLeftComponent(LeftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
        ManageCustomer mc = new ManageCustomer(CardSequenceJPanel,travelAgency);
        CardSequenceJPanel.add("ManageCustomer",mc);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_CustomerActionPerformed

    private void ManageAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAirlinersActionPerformed
        // TODO add your handling code here:
        AirlinerLogin al = new AirlinerLogin(CardSequenceJPanel, airlinerDirectory,travelAgency);
        CardSequenceJPanel.add("AirlinerLoginJPanel",al);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_ManageAirlinersActionPerformed

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
        WorkAreaAirliner waa = new WorkAreaAirliner(CardSequenceJPanel, airlinerDirectory,travelAgency);
        CardSequenceJPanel.add("WordAreaJPanel",waa);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton Customer;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton ManageAirliners;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
