/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Busniess.TravelAgencyClass;
import UserInterface.ManageAirlines.SearchFlight;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author varad
 */
public class ManageCustomerBookings extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerBookings
     */
    private JPanel CardSequenceJPanel;
    private TravelAgencyClass travelAgency;
    public ManageCustomerBookings(JPanel CardSequenceJPanel,TravelAgencyClass travelAgency) {
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.travelAgency = travelAgency;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBookFlight = new javax.swing.JButton();
        btnViewCustomers = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        btnBookFlight.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnBookFlight.setText("BookFlight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnViewCustomers.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnViewCustomers.setText("View Customers");
        btnViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(btnViewCustomers)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnBookFlight)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(btnViewCustomers)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
         SearchFlight ac = new SearchFlight(CardSequenceJPanel, travelAgency);
        CardSequenceJPanel.add("CreateFlight",ac);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomersActionPerformed
 ManageCustomer ac = new ManageCustomer(CardSequenceJPanel, travelAgency);
        CardSequenceJPanel.add("CreateFlight",ac);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCustomersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnViewCustomers;
    // End of variables declaration//GEN-END:variables
}
