/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Busniess.CustomerDirectory;
import javax.swing.JOptionPane;
import Busniess.Customer;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import javax.swing.table.TableModel;
import Busniess.AirlinerDirectory;
import UserInterface.ManageAirlines.SearchFlight;
import Busniess.Airliner;
import Busniess.Airplane;
import Busniess.Flight;
import Busniess.TravelAgencyClass;
import UserInterface.ManageAirlines.AirlinerLogin;
import UserInterface.ManageAirlines.Seats;
/**
 *
 * @author varad
 */
public class ShowCustomer extends javax.swing.JPanel {
    private JPanel CardSequenceJPanel;
    private TravelAgencyClass travelAgency;
    private Flight flight;
    /**
     * Creates new form ShowCustomer
     */
    public ShowCustomer(JPanel cjp,TravelAgencyClass travelAgency,Flight flight) {
        initComponents();
        this.CardSequenceJPanel = cjp;
        this.travelAgency = travelAgency;
        this.flight = flight;
        
        refreshTable();
    }
         public void refreshTable() {
        int rowCount = tblCustomers.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tblCustomers.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Customer c : travelAgency.getCustomerDirectory().getCustomerDict()) {
            Object row[] = new Object[5];
            row[0] = c;
            row[1] = c.getLastName();
            row[2] = c.getAge();
            row[3] = c.getId();
            row[4] = c.getAddress();
            model.addRow(row);
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Age", "Customer Id", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblCustomers);

        btnSelect.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        int row = tblCustomers.getSelectedRow();
         if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Customer customer = (Customer)tblCustomers.getValueAt(row, 0);       
      Seats seats = new Seats(CardSequenceJPanel,travelAgency,flight,customer);
        CardSequenceJPanel.add("ManageFlights",seats);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);   
    }//GEN-LAST:event_btnSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomers;
    // End of variables declaration//GEN-END:variables
}
