/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;
import Busniess.Airplane;
import Busniess.AirplaneDirectory;
import Busniess.Airliner;
import Busniess.TravelAgencyClass;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UserInterface.ManageAirlines.AddAirplane;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author varad
 */
public class AirplaneLogin extends javax.swing.JPanel {
    JPanel CardSequenceJPanel;
    //AirplaneDirectory airplaneDirectory;
    private Airliner airliner;
    private TravelAgencyClass travelAgency;
    
    
    /**
     * Creates new form AirplaneLogin
     */
    public AirplaneLogin(JPanel cjp, Airliner aa,TravelAgencyClass travelAgency) {
        initComponents();
        CardSequenceJPanel = cjp;
        airliner = aa;
        this.travelAgency = travelAgency;
        airlinername.setText(airliner.getAirlinerName());
        refreshTable();
    }
    public void refreshTable() {
        int rowCount = airplaneTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)airplaneTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Airplane a : airliner.getAirplaneDirectory().getAirplaneDict()) {
            Object row[] = new Object[1];
            row[0] = a;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneTable = new javax.swing.JTable();
        backjButton2 = new javax.swing.JButton();
        removeairliner = new javax.swing.JButton();
        addairliner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        airlinername = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Airplane detials");

        airplaneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Airplanes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airplaneTable);

        backjButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        removeairliner.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        removeairliner.setText("Remove");
        removeairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeairlinerActionPerformed(evt);
            }
        });

        addairliner.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        addairliner.setText("Add Airplanes");
        addairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addairlinerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("Airliner Name :-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backjButton2)
                        .addGap(18, 18, 18)
                        .addComponent(removeairliner)
                        .addGap(18, 18, 18)
                        .addComponent(addairliner))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(airlinername, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addairliner)
                    .addComponent(removeairliner)
                    .addComponent(backjButton2))
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
      backAction();
    
    }//GEN-LAST:event_backjButton2ActionPerformed
    private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirliners manageairplanes = (ManageAirliners) component;
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }
    
    private void removeairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeairlinerActionPerformed
        // TODO add your handling code here:
        int row = airplaneTable.getSelectedRow();

        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airplane a = (Airplane)airplaneTable.getValueAt(row, 0);
        airliner.getAirplaneDirectory().removeAirplane(a);
        refreshTable();
    }//GEN-LAST:event_removeairlinerActionPerformed

    private void addairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addairlinerActionPerformed
        // TODO add your handling code here:

        //int i=1;
        AddAirplane aa = new AddAirplane(CardSequenceJPanel, airliner,travelAgency);
        CardSequenceJPanel.add("AddAirliner", aa);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_addairlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addairliner;
    private javax.swing.JTextField airlinername;
    private javax.swing.JTable airplaneTable;
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeairliner;
    // End of variables declaration//GEN-END:variables
}
