/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;
import Busniess.Airliner;
import Busniess.Airplane;
import Busniess.Flight;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.ManageAirlines.Seats;
import java.awt.Component;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import Busniess.AirlinerDirectory;
import Busniess.Customer;
import Busniess.TravelAgencyClass;
/**
 *
 * @author varad
 */
public class SearchFlight extends javax.swing.JPanel {
      private JPanel CardSequenceJPanel;
      private TravelAgencyClass travelAgency;
     private Customer customer;
     
    /**
     * Creates new form SearchFlight
     */
    public SearchFlight(JPanel cjp,TravelAgencyClass travelAgency) {
        initComponents();
        this.CardSequenceJPanel = cjp;
        this.travelAgency = travelAgency;
      
       
     
      
    }
    
    
     public void populate() {
        int rowCount = tblSearchFlight.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tblSearchFlight.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Flight flight : travelAgency.getMasterFlightSchedule().getFlightSchedule().getFlightDict()) {
            if(flight.getFrom().equalsIgnoreCase(txtSource.getText()) &&
                    flight.getTo().equalsIgnoreCase(txtDestination.getText()))
            {
                Object row[] = new Object[5];
            row[0] = flight;
            row[1] = flight.getFrom();
            row[2] = flight.getTo();
            row[3] = flight.getTime();
            row[4] = flight.getDate();
            model.addRow(row);
            }
            
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchFlight = new javax.swing.JTable();
        BookSeat = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        tblSearchFlight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblSearchFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "From", "To", "time", "date"
            }
        ));
        jScrollPane1.setViewportView(tblSearchFlight);

        BookSeat.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BookSeat.setText("Book Seat >>");
        BookSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSeatActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSearch.setText("Search Flight");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Source : -");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("Destination: -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BookSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BookSeat)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BookSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSeatActionPerformed
        // TODO add your handling code here:
        int row = tblSearchFlight.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight flight = (Flight)tblSearchFlight.getValueAt(row, 0);
       
//        Seats ss = new Seats(CardSequenceJPanel, flight,travelAgency);
//        CardSequenceJPanel.add("BookSeat", ss);
//        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
//        layout.next(CardSequenceJPanel);
            BookingCustomer bookingCustomer = new BookingCustomer(CardSequenceJPanel, flight,travelAgency);
            CardSequenceJPanel.add("BookSeat", bookingCustomer);
             CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
             layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_BookSeatActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtSource.getText().isEmpty() || txtDestination.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Please enter source and destination");
        }
        else{
        populate();
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookSeat;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearchFlight;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
