/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import Busniess.Customer;
import Busniess.Flight;
import Busniess.TravelAgencyClass;
import UserInterface.Customer.ShowCustomer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author varad
 */
public class BookingCustomer extends javax.swing.JPanel {
    private TravelAgencyClass  travelAgency;
    private JPanel CardSequenceJPanel;
    private Flight flight;
    private Customer customer;
    /**
     * Creates new form BookingCustomer
     */
    public BookingCustomer( JPanel CardSequenceJPanel ,Flight flight,TravelAgencyClass  travelAgency) {
        initComponents();
        this.travelAgency = travelAgency;
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.flight = flight;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExistingCustomer = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        btnExistingCustomer.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnExistingCustomer.setText("Existing Customer");
        btnExistingCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingCustomerActionPerformed(evt);
            }
        });

        btnNewCustomer.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnNewCustomer.setText("New Customer");
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Booking Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExistingCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(btnNewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnExistingCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnNewCustomer)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        // TODO add your handling code here:
         
        Seats seats = new Seats(CardSequenceJPanel,travelAgency,flight,customer);
        CardSequenceJPanel.add("seats",seats);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void btnExistingCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingCustomerActionPerformed
        // TODO add your handling code here:
       ShowCustomer showCustomer = new ShowCustomer(CardSequenceJPanel,travelAgency,flight);
        CardSequenceJPanel.add("ManageFlights",showCustomer);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);  
    }//GEN-LAST:event_btnExistingCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExistingCustomer;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
