/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;
import Busniess.Airliner;
import Busniess.Airplane;
import Busniess.Flight;
import Busniess.FlightSchedule;
import Busniess.TravelAgencyClass;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UserInterface.ManageAirlines.ManageFlights;
/**
 *
 * @author varad
 */
public class CreateFlight extends javax.swing.JPanel {
    private Airliner airliner;
    private TravelAgencyClass travelAgency;
    JPanel CardSequenceJPanel;
    /**
     * Creates new form CreateFlight
     */
    public CreateFlight(JPanel cjp,Airliner airliner,TravelAgencyClass travelAgency) {
        initComponents();
        CardSequenceJPanel = cjp;
        this.travelAgency = travelAgency;
        this.airliner = airliner;
        cbxAirplaneName.removeAllItems();
       for(Airplane airplane : airliner.getAirplaneDirectory().getAirplaneDict()) {
           cbxAirplaneName.addItem(airplane);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FlightNoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ToText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FromText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TimeText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DueDateText = new javax.swing.JTextField();
        addFlights = new javax.swing.JButton();
        backtomanagflights = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxAirplaneName = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Add New Flight");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("Flight No :-");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("To :-");

        ToText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("From :-");

        FromText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("Time :-");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Due Date :-");

        addFlights.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        addFlights.setText("Create Flight");
        addFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightsActionPerformed(evt);
            }
        });

        backtomanagflights.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backtomanagflights.setText("<<Back");
        backtomanagflights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtomanagflightsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("Airplane Name : -");

        cbxAirplaneName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAirplaneName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAirplaneNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backtomanagflights)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFlights)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ToText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(FromText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 145, Short.MAX_VALUE)))
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FlightNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FlightNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DueDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlights)
                    .addComponent(backtomanagflights))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ToTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToTextActionPerformed

    private void FromTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromTextActionPerformed

    private void addFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightsActionPerformed
        // TODO add your handling code here:
        if(FlightNoText.getText().isEmpty()||FromText.getText().isEmpty()||ToText.getText().isEmpty()||TimeText.getText().isEmpty()||DueDateText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all the fields");
            return;
        }
        try{
            Double.parseDouble(TimeText.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter time in proper format ");
            return;
        }
        
        Flight flight = airliner.getFlightSchedule().addFlight();
        Airplane airplane = (Airplane)cbxAirplaneName.getSelectedItem();
        flight.setAirplane(airplane);
        flight.setFlightNo(FlightNoText.getText());
        flight.setFrom(FromText.getText());
        flight.setTo(ToText.getText());
        flight.setTime(Double.parseDouble(TimeText.getText()));
        flight.setDate(DueDateText.getText());
        travelAgency.getMasterFlightSchedule().getFlightSchedule().addtoMasterFlight(flight);
        
     //   flight.setAirplane(airplane.getAirplaneName());
            JOptionPane.showMessageDialog(null, "flight successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_addFlightsActionPerformed

    private void backtomanagflightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtomanagflightsActionPerformed
        // TODO add your handling code here:
        backAction();
        
    }//GEN-LAST:event_backtomanagflightsActionPerformed

    private void cbxAirplaneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAirplaneNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAirplaneNameActionPerformed
    private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlights manageFlights = (ManageFlights) component;
        manageFlights.refreshTable();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DueDateText;
    private javax.swing.JTextField FlightNoText;
    private javax.swing.JTextField FromText;
    private javax.swing.JTextField TimeText;
    private javax.swing.JTextField ToText;
    private javax.swing.JButton addFlights;
    private javax.swing.JButton backtomanagflights;
    private javax.swing.JComboBox cbxAirplaneName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
