/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;
import Busniess.Airliner;
import Busniess.Airplane;
import Busniess.Flight;
import Busniess.TravelAgencyClass;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.ManageAirlines.Seats;
import java.awt.Component;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author varad
 */
public class ManageFlights extends javax.swing.JPanel {
       
         JPanel CardSequenceJPanel;
         Airliner airliner;
         DefaultTableModel model;
         private TravelAgencyClass travelAgency;
    /**
     * Creates new form ManageFlights
     */
    public ManageFlights(JPanel cjp,Airliner airliner,TravelAgencyClass travelAgency ) {
        initComponents();
        this.CardSequenceJPanel = cjp;
       
        this.airliner = airliner;
        this.travelAgency = travelAgency;
      //  sNameTextField.setText(airliner.getAirplaneDirectory()getAirplaneName());
        //airlinerText.setText(airliner.getAirlinerName());
        refreshTable();
    }
         public void refreshTable() {
        int rowCount = FlightdetialsTable.getRowCount();
        model = (DefaultTableModel)FlightdetialsTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
       /* for(Airplane a : airliner.getAirplaneDirectory().getAirplaneDict()) {
            Object row[] = new Object[1];
            row[0] = a;
            model.addRow(row);
        }*/
        
        for(Flight f : airliner.getFlightSchedule().getFlightDict()) {
            //Airplane a : airliner.getAirplaneDirectory().getAirplaneDict();
            Object row[] = new Object[7];
            row[0] = f;
            row[1] = f.getFrom();
            row[2] = f.getTo();
            row[3] = f.getTime();
            row[4] = f.getDate();
       //     row[5] = f.getSeats();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
         private void filter(String query)
         {
             TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
             
             FlightdetialsTable.setRowSorter(tr);
             tr.setRowFilter(RowFilter.regexFilter(query));
         }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightdetialsTable = new javax.swing.JTable();
        delButton5 = new javax.swing.JButton();
        createPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Airliners");

        FlightdetialsTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FlightdetialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight no", "From", "To", "time", "date"
            }
        ));
        jScrollPane1.setViewportView(FlightdetialsTable);

        delButton5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        delButton5.setText("Delete Flight(s)");
        delButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButton5ActionPerformed(evt);
            }
        });

        createPButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        createPButton.setText("Create New Flight >>");
        createPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPButtonActionPerformed(evt);
            }
        });

        backButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delButton5)
                        .addGap(18, 18, 18)
                        .addComponent(createPButton)))
                .addContainerGap(400, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delButton5)
                    .addComponent(createPButton))
                .addGap(59, 59, 59)
                .addComponent(backButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButton5ActionPerformed
        // TODO add your handling code here:
        int row = FlightdetialsTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight flight = (Flight)FlightdetialsTable.getValueAt(row, 0);
        airliner.getFlightSchedule().removeFlight(flight);
        travelAgency.getMasterFlightSchedule().getFlightSchedule().removeFlight(flight);
      //  airplane.getFlighDirectory().removeFlight(flight);
        refreshTable();
    }//GEN-LAST:event_delButton5ActionPerformed

    private void createPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPButtonActionPerformed
        CreateFlight cf = new CreateFlight(CardSequenceJPanel, airliner,travelAgency);
        CardSequenceJPanel.add("CreateFlight",cf);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_createPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backButton4ActionPerformed
    private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirliners manageAirliner = (ManageAirliners) component;
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FlightdetialsTable;
    private javax.swing.JButton backButton4;
    private javax.swing.JButton createPButton;
    private javax.swing.JButton delButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
