/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;
import Busniess.Airliner;
import Busniess.Airplane;
import Busniess.Customer;
import Busniess.FinalDatabase;
import Busniess.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Busniess.Seat;
import Busniess.TravelAgencyClass;



/**
 *
 * @author varad
 */
public class Seats extends javax.swing.JPanel {
      private JPanel CardSequenceJPanel;
      private Flight flight;
      private TravelAgencyClass travelAgency;
      private Customer customer ;
      private FinalDatabase finalDatabase;
      public boolean[][] seatBoolean;
      
    /**
     * Creates new form Seats
     */
    public Seats(JPanel cjp,TravelAgencyClass travelAgency,Flight flight,Customer customer) {
        initComponents();
        this.CardSequenceJPanel = cjp;
        this.flight = flight;
        this.customer = customer;
        this.travelAgency = travelAgency;
        //seatBoolean = flight.getSeat().isIsBooked();
        seatBoolean = flight.getSeat().isIsBooked();
        if(customer != null)
        {
            populateCustomer(customer);
        }
        if(!flight.getFlightNo().isEmpty())
        {
            populateFlightData(flight);
        }
        cbxSeat.removeAllItems();
        for(int i = 1; i < 26 ;i++)
        {
            for(int j = 65; j < 71; j++)
            {
                if(!flight.getSeat().isIsBooked()[i-1][j-65]);
                cbxSeat.addItem( (char)j + "" + (i));
            }
        }
    }
   
    
    public void populateCustomer(Customer customer)
    {
        txtFirstName.setText(customer.getFirstName());
        txtLastName.setText(customer.getLastName());
        txtAge.setText(Integer.toString(customer.getAge()));
        txtAddress.setText(customer.getAddress());
        txtId.setText(Integer.toString(customer.getId()));
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtId.setEnabled(false);
        txtAddress.setEnabled(false);
        txtAge.setEnabled(false);
        
    }
public void populateFlightData(Flight flight)
{
    txtFlightNo.setText(flight.getFlightNo());
    txtFrom.setText(flight.getFrom());
    txtTime.setText(Double.toString(flight.getTime()));
    txtTo.setText(flight.getTo());
    txtDate.setText(flight.getDate());
   // txtSeat.setText();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbxSeat = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel66.setText("Customer Details");
        add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 30));

        jLabel67.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel67.setText("Flight Detials");
        add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        jLabel68.setText("First Name");
        add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 260, -1));

        jLabel69.setText("Last Name");
        add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 10));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 260, -1));

        jLabel70.setText("Age");
        add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel72.setText("Address");
        add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, -1));

        jLabel73.setText("Flight No :-");
        add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        txtFlightNo.setEditable(false);
        add(txtFlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 260, -1));

        txtFrom.setEditable(false);
        add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, -1));

        jLabel75.setText("From :-");
        add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        txtTo.setEditable(false);
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 260, -1));

        jLabel76.setText("To :-");
        add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        jLabel77.setText("Time :-");
        add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 20));

        txtTime.setEditable(false);
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 260, -1));

        txtDate.setEditable(false);
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 260, 20));

        jLabel78.setText("Date :-");
        add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 20));

        jLabel79.setText("Seat :-");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 720, -1));

        btnBook.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 130, -1));

        jLabel71.setText("Id");
        add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 260, -1));

        cbxSeat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbxSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        if(txtFirstName.getText().isEmpty()||txtLastName.getText().isEmpty()||txtAge.getText().isEmpty()||txtAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
            return;
        }
        
        try{
            Integer.parseInt(txtAge.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Enter in proper time format");
        }
       
        
            
          Customer customer = travelAgency.getCustomerDirectory().addCustomer();
          FinalDatabase finalDatabase = travelAgency.getFinalDirectory().addFinalDatabase();
       // Airplane airplane = (Airplane)cbxAirplaneName.getSelectedItem();
        customer.setFirstName(txtFirstName.getText());
        customer.setLastName(txtLastName.getText());
        customer.setAge(Integer.parseInt(txtAge.getText()));
        customer.setAddress(txtAddress.getText());
        customer.setSeatNumber(cbxSeat.getSelectedItem().toString());
        
        String row_index =   customer.getSeatNumber().substring(1,customer.getSeatNumber().length());
        char col_index = customer.getSeatNumber().charAt(0);
        int column = (int)col_index;
        int row = Integer.parseInt(row_index.trim());
      //  seatBoolean[row -1][column - 65] = true;
      //  flight.getSeat().isIsBooked()[row -1][column - 65];
        if(seatBoolean[row -1][column - 65] ==true)
        {
                JOptionPane.showMessageDialog(null, "seat already booked",null,JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        flight.getSeat().setIsBooked(seatBoolean);
        seatBoolean[row -1][column - 65] = true;
        
       // int index = cbxSeat.getSelectedIndex();
        //cbxSeat.removeItemAt(index);

        JOptionPane.showMessageDialog(null, "flight booked successfully",null, JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnBookActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
