/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;
import Busniess.AirlinerDirectory;
import Busniess.TravelAgencyClass;
import UserInterface.Customer.ManageCustomerBookings;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author varad
 */
public class WorkAreaAirliner extends javax.swing.JPanel {
    private JPanel CardSequenceJPanel;
    private AirlinerDirectory airlinerDirectory;
    private TravelAgencyClass travelAgency;
    /**
     * Creates new form WorkAreaAirliner
     */
    public WorkAreaAirliner(JPanel cjp, AirlinerDirectory ad,TravelAgencyClass travelAgency) {
        initComponents();
        CardSequenceJPanel = cjp;
        airlinerDirectory = ad;
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageairliner = new javax.swing.JButton();
        bnManageCustomers = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Airliner Area - Add Airliner");

        manageairliner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageairliner.setText("Manage Airliner >>");
        manageairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageairlinerActionPerformed(evt);
            }
        });

        bnManageCustomers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnManageCustomers.setText("Manage Customer Bookings >>");
        bnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnManageCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(manageairliner, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(bnManageCustomers)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageairliner)
                    .addComponent(bnManageCustomers))
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageairlinerActionPerformed
        // TODO add your handling code here:
        ManageAirliner panel = new ManageAirliner(CardSequenceJPanel, airlinerDirectory,travelAgency);
        CardSequenceJPanel.add("ManageSupplierAdministrative", panel);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_manageairlinerActionPerformed

    private void bnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnManageCustomersActionPerformed
        // TODO add your handling code here:
        ManageCustomerBookings panel = new ManageCustomerBookings(CardSequenceJPanel,travelAgency);
        CardSequenceJPanel.add("ManageSupplierAdministrative", panel);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_bnManageCustomersActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnManageCustomers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageairliner;
    // End of variables declaration//GEN-END:variables
}
